# Generated by Django 3.2 on 2021-09-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Port', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
